### ISSUE TITLE
middleman-s3_sync version

### ISSUE THREAD

**Issue by chrisanderton** [alienfast/middleman-aws#4]
middleman-s3_sync is available in a 3.x and 4.x flavour - you need to specify the version of the gem in the gem file to lock-in the right version for the version of middleman you are using - might be worth documenting this.

**Comment by rosskevin** [comment]
Please [edit the README](https://github.com/alienfast/middleman-aws/blob/master/README.md) and submit, I'll happily accept.

**Comment by rosskevin** [comment]
Master has been updated for v4, waiting for dependency PR to be released before doing a gem release.
